# This is a basic workflow to help you get started with Actions

name: Ci Pr

# Controls when the action will run. Triggers the workflow pull request
# events only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set SHOULD_RUN flag
      run: |
        if [[ "${{github.event.head_commit.message}}" =~ (skip\ ci|ci\ skip) ]]; then
          echo "::set-env name=SHOULD_RUN::false"
        else
          echo "::set-env name=SHOULD_RUN::true"
        fi
    - name: get commit message
      run: |
        echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
        echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
    - name: show commit message
      run : |
        echo env.commitmsg
        echo steps.log.outputs.message
    - name: step1
      if: contains( env.commitmsg , 'skip' )
      run: echo hello
    - name: echo the value
      run: echo "${{github.event.head_commit.message}}"
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 12.x
      if: env.SHOULD_RUN == 'true'
    - name: Cache node_modules
      id: cache_node_modules
      uses: actions/cache@v1
      with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      if: env.SHOULD_RUN == 'true'
    - if: env.SHOULD_RUN == 'true' && steps.cache_node_modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive
