# This is a basic workflow to help you get started with Actions

name: Ci Pr

# Controls when the action will run. Triggers the workflow pull request
# events only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: test my action
      id: skip
      uses: atlwendy/retrieve-commit-messages-from-pr@master
    - name: get my action output
      run: echo ::set-env name=SHOULD_RUN::${{ steps.skip.outputs.match }}
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: echo env
      run: echo ${{ env.SHOULD_RUN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      if: env.SHOULD_RUN == 'true'
    - name: Cache node_modules
      id: cache_node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      if: env.SHOULD_RUN == 'true'
    - if: env.SHOULD_RUN == 'true' && steps.cache_node_modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive
