# This is a basic workflow to help you get started with Actions

name: Ci Pr

# Controls when the action will run. Triggers the workflow pull request
# events only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set SHOULD_RUN flag
      run: |
        if [[ "${{github.event.head_commit.message}}" =~ (skip\ ci|ci\ skip) ]]; then
          echo "::set-env name=SHOULD_RUN::false"
        else
          echo "::set-env name=SHOULD_RUN::true"
        fi
    # Runs a single command using the runners shell
    - name: should it be skipped?
      env:
        COMMIT_FILTER: "skip-ci"
      run: |
        # Get last commit message
        readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
        echo "last commit log: $last_commit_log"

        readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
        echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

        if [[ "$filter_count" -eq 0 ]]; then
          echo "all good, continue"
        else
          echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
          exit 78
        fi
    - name: echo the value
      run: echo "${{github.event.head_commit.message}}"
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 12.x
      if: env.SHOULD_RUN == 'true'
    - name: Cache node_modules
      id: cache_node_modules
      uses: actions/cache@v1
      with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      if: env.SHOULD_RUN == 'true'
    - if: env.SHOULD_RUN == 'true' && steps.cache_node_modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --non-interactive
